name: Test I/O

on:
  workflow_call:
    inputs:
      python-versions:
        type: string
        required: false
        default: '3.9'

jobs:
  test-io:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJSON(inputs.python-versions) }}

    steps:

    - name: Setup ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Dump data into file
      run: |
        echo "${{ matrix.python-version }}" >> py_ver
        echo "$(date)" >> py_ver
