name: Test logic

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        required: false
        default: ${{ github.actor }}

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Call github.actor
        run: echo ${{ github.actor }}

      - name: Call inputs.name
        run: echo ${{ inputs.name }}
