name: Logic tester for workflow calls

on:
  workflow_call:
    inputs:
      bool_var:
        type: boolean
        required: false
        default: false

jobs:

  bool:
    runs-on: ubuntu-latest

    steps:

    - name: Will return bool_var
      run: echo ${{ inputs.bool_var }}

    - name: Will return nothing
      run: echo ${{ github.event.inputs.bool_var }}

    - name: Will work if bool_var is false
      if: ${{ inputs.bool_var == false }}
      run: echo yay

    - name: Will work if bool_var is true
      if: inputs.bool_var
      run: echo yay

    - name: Set an environment TEST=127
      run: |
        cat ksdjf;asdjfk &> /dev/null
        echo "TEST=$?" >> $GITHUB_ENV
      shell: bash -x {0}

    - name: Test logic if ( {{ env.TEST }} != 0 )
      if: ( ${{ env.TEST }} != 0 )
      run: echo yay

    - name: Test logic if ${{ env.TEST }}
      if: ${{ env.TEST }}
      run: echo yay

    - name: Test logic if env.TEST
      if: env.TEST
      run: echo yay

    - name: Test logic if ( {{ env.TEST }} != 0 && {{ inputs.booL_var }} )
      if: ( ${{ env.TEST }} != 0 && ${{ inputs.bool_var }} == 'true' )
      run: echo yay

    - name: Test logic if both are True
      if: ( ${{ env.TEST }} && ${{ inputs.bool_var }} == 'true' )
      run: echo yay

