name: Test logic

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      name:
        type: string
        required: false
        default: ''
      bool_val:
        type: boolean
        required: false
        default: false

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Handle empty variables
        id: handler
        run: >
          if [ ${{ inputs.name }} ]; then
          echo "::set-output name=name::${{ inputs.name }}"; else
          echo "::set-output name=name::${{ github.actor }}"; fi

        # This will echo the inputs.name that it is fed, or github.actor if not fed.
      - name: Echo empty string variable
        run: echo ${{ steps.handler.outputs.name }}


        # Testing booleans
      - name: Echo boolean input
        run: echo ${{ github.event.inputs.bool_val }}

      - name: Test boolean input, if ${{ github.event.inputs.bool_val == 'false' }}
        if: ${{ github.event.inputs.bool_val == 'false' }}
        run: echo yay

      - name: Test boolean input, if github.event.inputs.bool_val == 'false'
        if: github.event.inputs.bool_val == 'false'
        run: echo yay

      - name: Test boolean input, if ( github.event.inputs.bool_val == 'false' )
        if: ( github.event.inputs.bool_val == 'false' )
        run: echo yay
