name: Test logic

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        required: false
        default: ''

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Handle variables beforehand
        id: handler
        run: >
          if [ ${{ inputs.name }} ]; then
          echo "::set-output name=name::${{ inputs.name }}"; else
          echo "::set-output name=name::${{ github.actor }}"; fi

      - name: Call handler.outputs
        run: echo ${{ steps.handler.outputs.name }}
