name: Test logic

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      name:
        type: string
        required: false
        default: ''
      bool_val:
        type: boolean
        required: false
        default: false

jobs:
  # str:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Handle empty variables
  #       id: handler
  #       run: >
  #         if [ ${{ inputs.name }} ]; then
  #         echo "::set-output name=name::${{ inputs.name }}"; else
  #         echo "::set-output name=name::${{ github.actor }}"; fi

  #     - name: Will be 'test-name' if pushed, github.actor if manual dispatch with no input
  #       run: echo ${{ steps.handler.outputs.name }}

  # bool:
  #   runs-on: ubuntu-latest

  #   steps:
    
  #     - name: Echo boolean input
  #       run: echo ${{ github.event.inputs.bool_val }}

  #     - name: Will succeed if manual dispatch
  #       if: ${{ github.event.inputs.bool_val == 'false' }}
  #       run: echo yay

  #     - name: Will succeed if manual dispatch
  #       if: github.event.inputs.bool_val == 'false'
  #       run: echo yay

  #     - name: Will succeed if manual dispatch
  #       if: ( github.event.inputs.bool_val == 'false' )
  #       run: echo yay

  # call_bool_true:
  #   uses: ./.github/workflows/logic_caller.yaml
  #   with:
  #     bool_var: true

  # call_bool_false:
  #   uses: ./.github/workflows/logic_caller.yaml
  #   with:
  #     bool_var: false

  # io:
  #   uses: ./.github/workflows/io_test.yaml
  #   with:
  #     python-versions: >
  #       ["3.10", "3.9", "3.8"]

  test_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.10
          - 3.9
          - 3.8

    steps:
    - name: Set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Write to file
      run: |
        echo "${{ matrix.python-version }}" >> py_ver
        echo "$(date)" >> py_ver

  view_file:
    runs-on: ubuntu-latest
    needs: test_matrix
    steps:
    - name: View file
      run: |
        cat py_ver
