name: Test logic

on:
  push:
    branches:
      - main
    inputs:
      name:
        type: string
        required: false
        default: test-name
      bool_val:
        type: boolean
        required: false
        default: false
  workflow_dispatch:
    inputs:
      name:
        type: string
        required: false
        default: ''
      bool_val:
        type: boolean
        required: false
        default: false

jobs:
  str:
    runs-on: ubuntu-latest

    steps:
      - name: Handle empty variables
        id: handler
        run: >
          if [ ${{ inputs.name }} ]; then
          echo "::set-output name=name::${{ inputs.name }}"; else
          echo "::set-output name=name::${{ github.actor }}"; fi

      - name: Will be 'test-name' if pushed, github.actor if manual dispatch with no input
        run: echo ${{ steps.handler.outputs.name }}

  bool:
    runs-on: ubuntu-latest

      steps:
    
      - name: Echo boolean input
        run: echo ${{ github.event.inputs.bool_val }}

      - name: Will succeed if manual dispatch
        if: ${{ github.event.inputs.bool_val == 'false' }}
        run: echo yay

      - name: Will succeed if manual dispatch
        if: github.event.inputs.bool_val == 'false'
        run: echo yay

      - name: Will succeed if manual dispatch
        if: ( github.event.inputs.bool_val == 'false' )
        run: echo yay
