name: Test logic

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      name:
        type: string
        required: false
        default: ''
      bool_val:
        type: boolean
        required: true
        default: true

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Handle empty variables
        id: handler
        run: >
          if [ ${{ inputs.name }} ]; then
          echo "::set-output name=name::${{ inputs.name }}"; else
          echo "::set-output name=name::${{ github.actor }}"; fi

      - name: Echo empty string variable
        run: echo ${{ steps.handler.outputs.name }}

      - name: Test boolean input, if ${{ inputs.bool_val == 'true' }}
        if: ${{ inputs.bool_val == 'true' }}
        run: echo ${{ inputs.bool_val }}

      - name: Test boolean input, if inputs.bool_val == 'true'
        if: inputs.bool_val == 'true'
        run: echo ${{ inputs.bool_val }}
